language: node_js
env:
  - NODE_ENV=production CI=true
node_js:
  - "10"
script:
  - yarn build
  - yarn test
deploy:
  skip_cleanup: true
  provider: surge
  project: ./build/
  domain: ergo-explorer.surge.sh
