language: node_js

sudo: true

env:
  - NODE_ENV=production CI=true

node_js:
  - "10"

services:
  - docker

install:
  - yarn global add typescript@3.8
  - yarn --production=false

before_script:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

script:
  - yarn build
  - yarn test:coverage

after_success:
  - codecov
