openapi: 3.0.0
info:
  version: 1.0.0
  title: Blockchain explorer
tags:
  - name: blocks
    description: Everything about blocks
paths:
  /blocks:
    get:
      tags:
        - blocks
      summary: Get list of blocks
      description: Get list of blocks sorted by height
      parameters:
        - name: offset
          in: query
          description: Offset
          schema:
            type: integer
        - name: limit
          in: query
          description: Limit
          schema:
            type: integer
      operationId: listBlocks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Block'
                  total:
                    type: integer
  '/blocks/{id}':
    parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
    get:
      summary: Get block by id
      tags:
        - blocks
      responses:
        '200':
          description: Ok
          content:
            'application/json':
              schema:
                type: object
                properties:
                  block:
                    $ref: '#/components/schemas/Block'
                  transactions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
                  interlinks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Interlink'
                  references:
                    type: object
                    properties:
                      nextId:
                        type: string
                      previousId:
                        type: string
components:
  schemas:
    Block:
      properties:
        id:
          type: string
          description: Block hash
        votes:
          type: string
        difficulty:
          type: integer
        timestamp:
          type: integer
        nonce:
          type: integer
        stateRoot:
          type: string
        nBits:
          type: integer
        height:
          type: integer
        parentId:
          type: string
        transactionsRoot:
          type: string
        adProofsRoot:
          type: string
        equihashSolutions:
          type: array
          items:
            type: integer
        transactionCount:
          type: integer
        transactionSum:
          type: number
    Interlink:
      properties:
        id:
          type: string
        level:
          type: integer
    Transaction:
      properties:
        id:
          type: string
        value:
          type: number
        type:
          type: string
          enum:
            - input
            - output
