version: '3.3'

services:
  ergo-explorer-node:
      container_name: ergo-explorer-node
      build:
        context: .
      volumes:
        - ${REACT_APP_APP_CONFIG:-./client/public/app.config.js}:/usr/src/app/build/client/app.config.js
      ports:
        - '80:80'
